### ISSUE TITLE
Разобраться с работой алгоритма по сегментации областей на изображении

### ISSUE THREAD

**Issue by SergeyMorugin** [SergeyMorugin/GraphPod#12]

**Comment by IlyaYuzhno** [comment]
1. !!!Decompose image to graph edges with weights - DONE!!!
2. Sort edges by weights and compose segments - TODO
3. Return segments to pixels RGB - TODO
4. !!!Create new image from segments pixel data RGB - DONE!!!

**Comment by IlyaYuzhno** [comment]
Update:
 1. Decompose image to graph edges with weights - DONE
 2. Sort edges by weight and compose segments: define one and only parent for each pixel according to weight. Segment = pixels group with one parent (parent = graph tree root)
 3.  Go through segments and find each parent one by one
 4. Take random color according by parent number
 5. Create new image with colors
