### ISSUE TITLE
Research and decomposition the creating app tasks, add they to github project

### ISSUE THREAD

**Issue by SergeyMorugin** [SergeyMorugin/GraphPod#14]

**Comment by dvandyshev** [comment]
Главный экран приложения
	Имопрт фотографии из фотоальбома
	Импорт фотографии с камеры
	Имопрт потокового изображения
Экран демонстрации
	Вывод изображения
	Формирование сегментированного изображения 
	Вывод результата работы поверх импортированного изображения
