### ISSUE TITLE
Разобраться в способе упаковки своего кода в CocoaPods или SwiftPackages 

### ISSUE THREAD

**Issue by SergeyMorugin** [SergeyMorugin/GraphPod#5]
Как разработчик а я хочу иметь возможность удобно подключать эту библиотеку к своему проекту

**Comment by IlyaYuzhno** [comment]
Как сделать pod https://code.tutsplus.com/tutorials/creating-your-first-cocoapod--cms-24332

**Comment by IlyaYuzhno** [comment]
Как сделать package https://developer.apple.com/documentation/xcode/creating_a_standalone_swift_package_with_xcode
